### ISSUE TITLE
Setup Kanban board

### ISSUE THREAD

**Issue by lucy-sees** [lucy-sees/CulinaryCompass#11]
Hi,

We are a team of 2 members: 

1. Team member A: @jkanyi-web 
2. Team member B: @lucy-sees 

[Link](https://github.com/users/lucy-sees/projects/2/views/1) to the project

**Comment by zeff96** [comment]
### Status: CHANGES REQUIRED ♻️
Hi @lucy-sees and @jkanyi-web , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://media2.giphy.com/media/t8YPf3ACKeouLzEIvr/200w.webp?cid=ecf05e47ksdapb6k1rdp63370g9xfr1szjyu0o8slceoczrs&ep=v1_gifs_search&rid=200w.webp&ct=g)

## Highlights
:heavy_check_mark: kanban created and all columns added

## Required Changes ♻️

- [ ] Hello, Kindly make sure to add cards for integration and unit tests

![Screenshot from 2023-12-18 14-47-38](https://github.com/lucy-sees/CulinaryCompass/assets/112261237/c8a3a4cb-870e-421f-8043-9f9521b0e2c3)

- [ ] Hello, kindly pay attention to the workload, from the kanban, the workload is not fairly distributed, to foster a balanced workload, sum up points for each member and make sure the difference is not >=5

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by lucy-sees** [comment]
A card for integration and unit test.

![tests-card](https://github.com/lucy-sees/CulinaryCompass/assets/100368317/020ecfb0-a161-41db-8fae-f5d82dd18302)

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @jkanyi-web and @jkanyi-web,

✔️ Task points are well distributed

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
